openapi: 3.0.0
info:
  title: Imabulary API
  description: API documentation for the Imabulary API
  version: 1.0.0

paths:
  /quiz/learn:
    $ref: "./paths/quiz/learn.yaml"

  /feedback/categories:
    $ref: "./paths/feedback/categories.yaml"

  /feedback/create:
    $ref: "./paths/feedback/create.yaml"

  /flashcards/scan:
    $ref: "./paths/flashcards/scan.yaml"

  /flashcards/:
    $ref: "./paths/flashcards/flashcards.yaml"

  /flashcards/organize:
    $ref: "./paths/flashcards/organize.yaml"

  /flashcards/disorganize:
    $ref: "./paths/flashcards/disorganize.yaml"

  /flashcards/like:
    $ref: "./paths/flashcards/like.yaml"

  /flashcards/dislike:
    $ref: "./paths/flashcards/dislike.yaml"

  /sets:
    $ref: "./paths/sets/sets.yaml"

  /sets/{id}:
    $ref: "./paths/sets/sets-id.yaml"

  /users:
    $ref: "./paths/users/users.yaml"

  /wallet:
    $ref: "./paths/wallet/wallet.yaml"

  /wallet/collect:
    $ref: "./paths/wallet/collect-award.yaml"

components:
  schemas:
    $ref: "./components/schemas/index.yaml"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
