// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvNdKTfJcIeRvi3Psy1MRXNNmoBWXluC0',
    appId: '1:222626452683:android:77361b1bd591ed9e0ff74e',
    messagingSenderId: '222626452683',
    projectId: 'imabulary-fc20f',
    storageBucket: 'imabulary-fc20f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABWjnLQKACnyyJf6q4bXgKjFW7DAwGh2o',
    appId: '1:222626452683:ios:4b8d61be542ec4eb0ff74e',
    messagingSenderId: '222626452683',
    projectId: 'imabulary-fc20f',
    storageBucket: 'imabulary-fc20f.appspot.com',
    androidClientId:
        '222626452683-6e62oh12qg57dg31226f5amnldeftm5d.apps.googleusercontent.com',
    iosClientId:
        '222626452683-823iovqtt4e9aukg6rl8bkr6c34oj7r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.imabulary',
  );
}
