name: Deploy to GCP

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_NAME || 'imabulary' }}
      GOOGLE_COMPUTE_ZONE: ${{ secrets.GCP_ZONE || 'us-central1' }}
      GAR_LOCATION: ${{ secrets.GCP_GAR || 'us-central1-docker.pkg.dev/imabulary/my-app/backend' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
  
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GOOGLE_COMPUTE_ZONE }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --tag ${{ env.GAR_LOCATION }}:${{ github.run_number }}
        working-directory: ./server

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}:${{ github.run_number }}

      - name: Install JQ
        run: sudo apt-get --yes install jq

      - name: Deploy new instance and manage IPs
        run: |
          NEW_INSTANCE="instance-build-${{ github.run_number }}"
          MACHINE_TYPE="${{ secrets.GCP_MACHINE_TYPE || 'f1-micro' }}"
          gcloud beta compute instances create-with-container "$NEW_INSTANCE" \
            --machine-type=$MACHINE_TYPE \
            --container-image=${{ env.GAR_LOCATION }}:${{ github.run_number }} \
            --tags http-server,https-server \
            --zone ${{ env.GOOGLE_COMPUTE_ZONE }}-a --quiet

          OLD_INSTANCE=$(gcloud compute instances list --filter="EXTERNAL_IP=('prod-ip')" --zones $GOOGLE_COMPUTE_ZONE --format=json | jq '.[0].name' --raw-output)

          gcloud compute instances delete-access-config "$NEW_INSTANCE" \
            --access-config-name "external-nat" \
            --zone ${{ env.GOOGLE_COMPUTE_ZONE }}-a --quiet

          if [ "$OLD_INSTANCE" != "null" ]; then
            gcloud compute instances delete "$OLD_INSTANCE" \
              --zone ${{ env.GOOGLE_COMPUTE_ZONE }}-a --quiet
          fi

          gcloud compute instances add-access-config "$NEW_INSTANCE" \
            --access-config-name "external-nat" --address "prod-ip" \
            --zone ${{ env.GOOGLE_COMPUTE_ZONE }}-a --quiet
