name: Deploy to GCP

on:
  push:
    branches:
      - production
  pull_request:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_NAME || 'imabulary' }}
      GOOGLE_COMPUTE_ZONE: ${{ secrets.GCP_ZONE || 'us-central1-a' }}
      GAR_LOCATION: ${{ secrets.GCP_GAR || 'us-central1-docker.pkg.dev/imabulary/my-app' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"
  
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GOOGLE_COMPUTE_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --tag ${{ env.GAR_LOCATION }}:${{ github.run_number }
        working-directory: ./server

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}:${{ github.run_number }

      - name: Install JQ
        run: sudo apt-get --yes install jq

      - name: Deploy new instance and manage IPs
        run: |
          NEW_INSTANCE="instance-build-${{ github.run_number }}"
          MACHINE_TYPE="${{ secrets.GCP_MACHINE_TYPE || 'f1-micro' }}"
          gcloud beta compute instances create-with-container "$NEW_INSTANCE" \
            --machine-type=$MACHINE_TYPE \
            --container-image=${{ env.GAR_LOCATION }}:${{ github.run_number }} \
            --tags http-server,https-server \
            --zone $GOOGLE_COMPUTE_ZONE

          OLD_INSTANCE=$(gcloud compute instances list --filter="EXTERNAL_IP=('prod-ip')" --zones $GOOGLE_COMPUTE_ZONE --format=json | jq '.[0].name' --raw-output)

          gcloud compute instances delete-access-config "$NEW_INSTANCE" \
            --access-config-name "external-nat" \
            --zone $GOOGLE_COMPUTE_ZONE

          if [ "$OLD_INSTANCE" != "null" ]; then
            gcloud compute instances delete "$OLD_INSTANCE" --zone $GOOGLE_COMPUTE_ZONE
          fi

          gcloud compute instances add-access-config "$NEW_INSTANCE" \
            --access-config-name "external-nat" --address "prod-ip" \
            --zone $GOOGLE_COMPUTE_ZONE
